name: 'CMake Dependency Submission'
description: 'Calculates dependencies for a CMake project and submits the list to the GitHub Dependency Submission API'
author: 'Breno Cunha Queiroz'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    default: ${{ github.token }}
    required: false
  sourcePath:
    description: "Path to source tree containing CMakeLists.txt and *.cmake files"
    default: "${{ github.workspace }}"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
