name: 'CMake Dependency Submission'
description: 'Calculates dependencies for a CMake project and submits the list to the GitHub Dependency Submission API'
author: 'Breno Cunha Queiroz'
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  cmakeListsTxtPath:
    default: "${{ github.workspace }}/CMakeLists.txt"
    required: false
    description: "Path to CMakeLists.txt"
runs:
  using: 'node16'
  main: 'dist/index.js'
