name: 'Cmake Dependency Submission'
description: 'Calculates dependencies for a cmake project and submits the list to the Dependency Submission API'
author: 'Breno Cunha Queiroz'
branding:
  icon: 'check-circle'  
  color: 'blue'
inputs:
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner"
    required: false
    default: ${{ github.token }}
  testing-action:
    required: true
    description: 'Testing my first action'
    default: ''
runs:
  using: 'node16'
  main: 'lib/main.js'
