name: CMake Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: philips-forks/cmake-dependency-submission@main
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
          gh sbom -c  -l | jq
