name: CMake Dependency Submission
on:                        
  push:
    branches:
      - main               

jobs:
  dependency-submission:
    runs-on: ubuntu-latest 
    permissions: # The Dependency Submission API requires write permission
      contents: write      
    steps:
      - name: Checkout Repository     
        uses: actions/checkout@v3       

      - name: Dependency Submission
        uses: brenocq/cmake-dependency-submission@main
        with:
          testing-action: "Hello world!"  
