name: Build & test
on:
  pull_request:
   branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Build and run tests 
        run: npm rebuild && npm run all

      - name: Verify no uncommitted files
        run: '[ -z "$(git status --porcelain=v1 2>/dev/null)" ]'
        shell: bash
