name: Build & Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Build and run tests
        run: npm rebuild && npm run all
